sudo: false
language: java
compiler:
    - javac
jdk:
    - oraclejdk8
before_script:
    - cd src
script:
    - javac *.java
after_script:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)"
